sb/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from sb.views import first_view, customer_detail, main_logout

urlpatterns = [
    url(r'^logout/', main_logout, name='logout'),
	url(r'^$', login_required(first_view.as_view()), name='concept_1'),
    url(r'customerDetailed/(?P<pk>\d+)/$', login_required(customer_detail.as_view()), name='customer-detail'),
]

suvbra/urls.py
from django.conf.urls import patterns, include, url
from rest_framework import routers
from django.contrib import admin

from sb.views import cust_viewset, login_view

router = routers.DefaultRouter()
router.register(r'customers', cust_viewset)

urlpatterns = patterns('',
    url(r'^$', login_view.as_view(), name='login'),
	url(r'^Concept/', include('sb.urls', namespace='test')),
    url(r'^api/', include(router.urls, namespace='rest_api')),
    url(r'^admin/', include(admin.site.urls)),
)

sb/models.py
from django.db import models

class customer(models.Model):
	first_name = models.CharField(max_length=12)
	last_name = models.CharField(max_length=12)
	home_phone = models.CharField(max_length=10, blank=True)
	cell_phone = models.CharField(max_length=10, blank=True)
	email = models.EmailField(max_length=25, blank=True)
	full_address = models.CharField(max_length=25)
	alt_address = models.CharField(max_length=25, blank=True)
	city = models.CharField(max_length=12)
	state = models.CharField(max_length=12)
	zip_code = models.CharField(max_length=5)

sb/forms.py
from django import forms

from sb.models import customer

class customer_form(forms.ModelForm):
    class Meta:
        model = customer
        fields = [
            'first_name',
            'last_name',
            'home_phone',
            'cell_phone',
            'email',
            'full_address',
            'alt_address',
            'city',
            'state',
            'zip_code',
        ]

class login_form(forms.Form):
    user_name = forms.CharField(max_length=10, widget=forms.TextInput(attrs={'placeholder': 'User Name', 'class': 'form-control', 'id': 'inputUsername'}), required=True)
    user_pass = forms.CharField(max_length=10, widget=forms.PasswordInput(attrs={'placeholder': 'Password', 'class': 'form-control', 'id': 'inputPassword'}), required=True)

sb/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from rest_framework import viewsets
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import View, DetailView

from sb.serializers import CustSerializer
from sb.models import customer
from sb.forms import customer_form, login_form

class login_view(View):
    template_name = 'login/login.html'
    form_class = login_form

    def get(self, request):
        context = {'form': self.form_class()}
        return render(request, self.template_name, context)

    def post(self, request):
        context = {'form': self.form_class()}
        form = self.form_class(self.request.POST or None)
        if form.is_valid():
            this_user = form['user_name'].data
            this_pass = form['user_pass'].data
            get_user_logged = authenticate(username=this_user, password=this_pass)
            if get_user_logged:
                if get_user_logged.is_active:
                    login(request, get_user_logged)
                    return HttpResponseRedirect(reverse('test:concept_1'))
                else:
                    return HttpResponse('Account Disabled... ')
            else:
                return render(request, self.template_name, context)
        else:
            return render(request, self.template_name, context)

class first_view(View):
    template_name = 'suvbra/home.html'
    form_class = customer_form

    def get(self, request, *args, **kwags):
        context = {
            'form': self.form_class(),
            'customer_info': customer.objects.all(),
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        context = {
            'form': self.form_class(),
            'customer_info': customer.objects.all(),
        }
        form = self.form_class(self.request.POST or None)
        if form.is_valid():
            form.save()
        return render(request, self.template_name, context)

@login_required
def main_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('login'))

class customer_detail(DetailView):
    template_name = 'suvbra/cus_detail.html'
    model = customer

class cust_viewset(viewsets.ReadOnlyModelViewSet):
    queryset = customer.objects.all()
    serializer_class = CustSerializer

templates/home.html
<html>
<head>
	<title>Testing</title>
</head>
<body>
	<h1>WORKED!</h1>
</body>
</html>

templates/login/login.html
{% load bootstrap3 %}
<html>
  <head>
  <title>login</title>
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  </head>
<body>
  <div class="container">
      <form class="form-signin" method='post' action="">
        {% csrf_token %}
        <h2 class="form-signin-heading">Please sign in</h2>
        <label for="inputEmail" class="sr-only">Email address</label>
        {{ form.user_name }}
        <label for="inputPassword" class="sr-only">Password</label>
        {{ form.user_pass }}
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>
    </div>
</body>
</html>

templates/suvbra/base.html
{% load bootstrap3 %}
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    {% block bodycontent %}{% endblock %}
    <hr>
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <a href="{% url 'test:logout' %}">Logout</a>
        </div>
      </div>
    </div>
</body>
</html>

templates/suvbra/cus_detail.html
{% extends 'suvbra/base.html' %}
{% load bootstrap3 %}
{% block title %}Customer Detail{% endblock %}
{% block bodycontent %}
    <div class = "container">
        <div class="row">
            <div class="jumbotron">
                <h2>Information For Customer ID: {{ object.pk }}</h2>
                <p>First Name: {{ object.first_name }}</p>
                <p>Last Name: {{ object.last_name }}</p>
                {% if object.home_phone %}
                    <p>Home Phone: {{ object.home_phone }}</p>
                {% else %}
                    <p>Home Phone: - </p>
                {% endif %}
                {% if object.cell_phone %}
                    <p>Cell Phone: {{ object.cell_phone }}</p>
                {% else %}
                    <p>Cell Phone: - </p>
                {% endif %}
                {% if object.email %}
                    <p>Email: {{ object.email }}</p>
                {% else %}
                    <p>Email: - </p>
                {% endif %}
                <p>Full Address: {{ object.full_address }}</p>
                {% if object.alt_address %}
                    <p>Alt Address: {{ object.alt_address }}</p>
                {% else %}
                    <p>Alt Address: - </p>
                {% endif %}
                <p>City: {{ object.city }}</p>
                <p>State: {{ object.state }}</p>
                <p>Zip Code: {{ object.zip_code }}</p>
                <a href="{% url 'test:concept_1' %}"
                    <button type="button" class="btn btn-lg btn-link">Back</button>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

templates/suvbra/home.html
{% extends 'suvbra/base.html' %}
{% load bootstrap3 %}
{% block title %}Customer Entry{% endblock %}
{% block bodycontent %}
    <div class = "container">
        <div class="row">
            <div class="col-md-6">
            <form action="#" method="post" class="form">
              {% csrf_token %}
              {% bootstrap_form form %}
              {% buttons %}
                <button type="submit" class="btn btn-primary">
                  {% bootstrap_icon "star" %} Submit
                </button>
              {% endbuttons %}
            </form>
            </div>
        </div>
        {% if customer_info %}
            <div>
            <ul>
            {% for customers in customer_info %}
                <li><a href="{% url 'test:customer-detail' customers.id %}">{{ customers.first_name }}</a></li>
            {% endfor %}
            </ul>
            </div>
        {% else %}
            <div>
                <p>No Current Customers</p>
            </div>
        {% endif %}
    </div>
{% endblock %}